/** Rótulos das seções de entrega, compartilhados entre a tela e as exportações. */
export const ROTULOS_SECAO: Record<string, string> = {
  cabecalho: 'Cabeçalho',
  codigoCaso: 'Código do caso',
  dataElaboracao: 'Data de elaboração',
  classificacaoSigilo: 'Classificação de sigilo',
  resumoApuracao: 'Resumo da apuração',
  gravidade: 'Classificação da gravidade',
  nivel: 'Nível',
  justificativa: 'Justificativa',
  criteriosInvestigacao: 'Critérios de investigação',
  escutaAtiva: 'Escuta ativa',
  apuracaoFatos: 'Apuração de fatos',
  contextoAdicional: 'Contexto adicional',
  planoResolucao: 'Plano de resolução',
  embasamentoLegal: 'Embasamento legal e normativo',
  referencia: 'Referência',
  aplicacao: 'Aplicação',
  recomendacoesAdicionais: 'Recomendações adicionais',
  notaGuarda: 'Nota de guarda',
  limitacoesAnonimato: 'Limitações probatórias (denúncia anônima)',

  objetivoEstrategico: 'Objetivo estratégico',
  descricao: 'Descrição',
  roiEsperado: 'ROI esperado',
  kpis: 'KPIs',
  metodologia: 'Metodologia utilizada',
  nome: 'Nome',
  porQueEscolhida: 'Por que foi escolhida',
  planoAula: 'Plano de aula',
  modulo: 'Módulo / Atividade',
  duracao: 'Duração',
  recurso: 'Recurso necessário',
  roteiroSlides: 'Roteiro de slides',
  numero: 'Slide',
  titulo: 'Título',
  pontosChave: 'Pontos-chave',
  dicasFacilitacao: 'Dicas de facilitação',
  indicadoresAvaliacao: 'Indicadores de avaliação',
  reacao: 'Reação',
  aprendizagem: 'Aprendizagem',
  comportamento: 'Comportamento',
  resultado: 'Resultado',
  promptCanva: 'Prompt para o Canva',

  formato: 'Formato',
  assunto: 'Assunto',
  corpo: 'Comunicação',
  escalonamento: 'Escalonamento',
  necessario: 'Necessário',
  situacao: 'Situação',
  acaoRecomendada: 'Ação recomendada',
  orientacaoConducao: 'Como conduzir',

  diagnostico: 'Diagnóstico',
  analiseEstrategica: 'Análise estratégica',
  pessoas: 'Pessoas',
  processos: 'Processos',
  cultura: 'Cultura',
  resultados: 'Resultados',
  orientacao: 'Orientação',
  recomendacao: 'Recomendação',
  fundamentacao: 'Fundamentação',
  fonte: 'Fonte',
  indicadoresSugeridos: 'Indicadores sugeridos',

  promptGerado: 'Prompt gerado',
  persona: 'Persona',
  missao: 'Missão',
  fluxoAcao: 'Fluxo de ação',
  dominios: 'Domínios de atuação',
  formatoSaida: 'Formato de saída',
  tomDeVoz: 'Tom de voz',
  restricoes: 'Restrições',
  orientacoesGerais: 'Orientações gerais',
  porQueFunciona: 'Por que este prompt funciona',
  tecnicasAplicadas: 'Técnicas aplicadas',

  acao: 'Ação',
  responsavel: 'Responsável',
  prazo: 'Prazo',
};
